import sgMail from "@sendgrid/mail";
import { NextRequest, NextResponse } from "next/server";

sgMail.setApiKey(process.env.SENDGRID_API_KEY!);

export async function POST(req: NextRequest) {
  try {
    const body = await req.json();

    console.log("FROM:", process.env.SENDGRID_FROM_EMAIL);
    console.log("TO:", body.agentEmail);

    const fromEmail = process.env.SENDGRID_FROM_EMAIL;
    const toEmail = body.agentEmail;

    if (!fromEmail || !toEmail) {
      return NextResponse.json(
        { success: false, error: "Invalid email configuration" },
        { status: 400 },
      );
    }

    const utilitiesRows = Object.entries(body.utilities || {})
      .map(
        ([key, value]) => `
      <tr>
        <td style="padding:8px;border:1px solid #ddd;text-transform:capitalize;">
          ${key}
        </td>
        <td style="padding:8px;border:1px solid #ddd;">
          ${value}
        </td>
      </tr>
    `,
      )
      .join("");

    const msg = {
      to: toEmail,
      from: fromEmail,
      subject: "Utility Information Submitted",
      html: `
  <div style="font-family: Arial, sans-serif; background:#f4f6f8; padding:20px;">
    <div style="max-width:600px; margin:0 auto; background:#ffffff; padding:20px; border-radius:8px;">
      
      <h2 style="margin-top:0; color:#333;">Utility Submission</h2>
      
      <p style="margin:6px 0;"><strong>Agent:</strong> ${body.agentName}</p>
      <p style="margin:6px 0;"><strong>Property:</strong> ${body.propertyAddress}</p>
      <p style="margin:6px 0;"><strong>Submitted:</strong> ${body.submittedDate}</p>

      <h3 style="margin-top:20px;">Utility Details</h3>

      <table style="width:100%; border-collapse:collapse; margin-top:10px;">
        <thead>
          <tr style="background:#f0f0f0;">
            <th style="padding:8px; border:1px solid #ddd; text-align:left;">Utility</th>
            <th style="padding:8px; border:1px solid #ddd; text-align:left;">Provider</th>
          </tr>
        </thead>
        <tbody>
          ${utilitiesRows}
        </tbody>
      </table>

      <p style="margin-top:20px; font-size:12px; color:#777;">
        This email was automatically generated by your system.
      </p>

    </div>
  </div>
  `,
    };

    const response = await sgMail.send(msg);
    console.log("SendGrid Success:", response);

    return NextResponse.json({ success: true });
  } catch (error: any) {
    console.error("SendGrid Error:", error.response?.body || error);
    return NextResponse.json({ success: false }, { status: 500 });
  }
}
